### ISSUE TITLE
Access local environment / different endpoint

### ISSUE THREAD

**Issue by MickL** [mastertinner/s3manager#6]
How may I access a different environment? Normally with aws-sdk we can specify and endpoint (e.g. `http://localhost:4572`) but is this possible in s3manager, too? 

Currently I get:

> s3-manager_1        | 2020/05/01 13:24:49 GET   /       34.807µs
> s3-manager_1        | 2020/05/01 13:24:49 error listing buckets: Get "https://s3.dualstack.us-east-1.amazonaws.com/": x509: certificate signed by unknown authority

Here is my docker-compose:

```
s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8082:8080
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - REGION=eu-central-1
      - ENVIRONMENT=http://localhost:4572
```

P.S. Could you please add a docker-compose example to the docker-hub? Currently it is just a copy of the readme which was not very useful (explains how to build an image but on docker-hub I already have an image). This could also explain which environment variables can be set, currently I have to guess them... Example: https://hub.docker.com/r/taydy/dynamodb-manager/

P.P.S. A screenshot in the readme of the GUI would have been nice, too :)
