### ISSUE TITLE
Setting endpoint: error creating s3 client: Endpoint url cannot have fully qualified paths

### ISSUE THREAD

**Issue by MickL** [mastertinner/s3manager#7]
I get this error:

> error creating s3 client: Endpoint url cannot have fully qualified paths

docker-composer.yaml:

```
s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8082:8080
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - REGION=eu-central-1
      - ENDPOINT=http://localhost
      - PORT=4572
```

I tried:

- http://localhost/
- http://localhost
- localhost/ (nothing happens / does not start)
- localhost (error: Endpoint: localhost/ does not follow ip address or domain name standards)

**Comment by mastertinner** [comment]
The protocol should not be part of the endpoint. Furthermore, you need to be aware that the `PORT` environment variable refers to the port s3manager will run on. Not the port your S3 server runs on. So I think in your case it should be:

```yaml
s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8082:8080
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - ENDPOINT=localhost:4572
```

**Comment by MickL** [comment]
Got it, thank you!!

But `USE_SSL` does not seem to work. I get

> error listing buckets: Get "https://localhost:4572/": dial tcp 127.0.0.1:4572: connect: connection refused

With: 
```
  s3-manager:
    image: mastertinner/s3manager
    ports:
      - 8002:8080
    environment:
      - ACCESS_KEY_ID=abc
      - SECRET_ACCESS_KEY=def
      - REGION=eu-central-1
      - ENDPOINT=localhost:4572
      - PORT=8080
      - USE_SSL=false
```

P.S. May you want to add this to the readme so the next person who wants to use it local has no issues? :)
